/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Steve Karanja
 */
public class Viewgrades extends javax.swing.JFrame {

    /**
     * Creates new form Viewgrades
     */
    public Viewgrades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        classLevel = new javax.swing.JComboBox<>();
        btnClassSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        regno = new javax.swing.JTextField();
        btnRegSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradesTable = new javax.swing.JTable();
        btnHome = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 250, 154));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIEW GRADES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(70, 130, 180));

        classLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class 1", "Class 2", "Class 3", "Class 4", "Class 5", "Class 6", "Class 7", "Class 8" }));

        btnClassSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        btnClassSearch.setText("SEARCH");
        btnClassSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassSearchActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("OR");

        regno.setToolTipText("");

        btnRegSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        btnRegSearch.setText("SEARCH");
        btnRegSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegSearchActionPerformed(evt);
            }
        });

        if (Main.listOfStudents.isEmpty()) {
            btnClassSearch.setEnabled(false);
            regno.setEditable(false);
            btnRegSearch.setEnabled(false);
        }

        Object columnNames[] = {"Class", "Registration Number", "Name", "English", "Kiswahili", "Math", "Science", "S.S/C.R.E", "Total", "Average"};
        //Object[] rowData;
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        if (!Main.listOfStudents.isEmpty()) {
            for (Student s : Main.listOfStudents ) {
                if (s.studentGrades != null) {
                    Grade grade = s.studentGrades;
                    int total = grade.calculateTotal();
                    String average = Double.toString(total/5);
                    Object rowData[] = {s.getGradeLevel(), s.getRegno(),  s.getFname() +"  "+s.getLname(), grade.getEnglish()+"  "+Grade.genGrade(grade.getEnglish()),
                            grade.getKiswahili()+"  "+Grade.genGrade(grade.getKiswahili()), grade.getMaths()+"  "+Grade.genGrade(grade.getMaths()),
                            grade.getScience()+"  "+Grade.genGrade(grade.getScience()), grade.getSsre()+"  "+Grade.genGrade(grade.getSsre()), total, average+"  "+Grade.genGrade(average)};
                    model.addRow(rowData);
                }
            }
        }

        gradesTable.setModel(model);
        jScrollPane1.setViewportView(gradesTable);

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        btnHome.setText("Back to Dashboard");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(70, 130, 180));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registration Number");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClassSearch)
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regno, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClassSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(regno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClassSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassSearchActionPerformed
        Object columnNames[] = {"Class", "Registration Number", "Name", "English", "Kiswahili", "Math", "Science", "S.S/C.R.E", "Total", "Average"};
        //Object[] rowData;
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        if (!Main.listOfStudents.isEmpty()) {
            for (Student s : Main.listOfStudents ) {
                String gradeClass = classLevel.getSelectedItem().toString();
                if (s.studentGrades != null && s.gradeLevel.equals(gradeClass)) {
                    Grade grade = s.studentGrades;
                    int total = grade.calculateTotal();
                    String average = Double.toString(total/5);
                    Object rowData[] = {s.getGradeLevel(), s.getRegno(),  s.getFname() +"  "+s.getLname(), grade.getEnglish()+"  "+Grade.genGrade(grade.getEnglish()),
                            grade.getKiswahili()+"  "+Grade.genGrade(grade.getKiswahili()), grade.getMaths()+"  "+Grade.genGrade(grade.getMaths()),
                            grade.getScience()+"  "+Grade.genGrade(grade.getScience()), grade.getSsre()+"  "+Grade.genGrade(grade.getSsre()), total, average+"  "+Grade.genGrade(average)};
                    model.addRow(rowData);
                }
            }
        }

        gradesTable.setModel(model);
        jScrollPane1.setViewportView(gradesTable);


    }//GEN-LAST:event_btnClassSearchActionPerformed

    private void btnRegSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegSearchActionPerformed
        if (regno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Registration Number");
            return;
        }

        int position = Application.searchStudent(regno.getText());
        if (position == Integer.MAX_VALUE) {
            JOptionPane.showMessageDialog(null, "Student Does Not Exist!");
            return;
        }

        Student s = Main.listOfStudents.get(position);
        if (s.getStudentGrades() == null) {
            JOptionPane.showMessageDialog(null, "Student Does Not Have Grades!");
            return;
        }

        Object columnNames[] = {"Class", "Registration Number", "Name", "English", "Kiswahili", "Math", "Science", "S.S/C.R.E", "Total", "Average"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        Grade grade = s.studentGrades;
        int total = grade.calculateTotal();
        String average = Double.toString(total/5);
        Object rowData[] = {s.getGradeLevel(), s.getRegno(),  s.getFname() +"  "+s.getLname(), grade.getEnglish()+"  "+Grade.genGrade(grade.getEnglish()),
                grade.getKiswahili()+"  "+Grade.genGrade(grade.getKiswahili()), grade.getMaths()+"  "+Grade.genGrade(grade.getMaths()),
                grade.getScience()+"  "+Grade.genGrade(grade.getScience()), grade.getSsre()+"  "+Grade.genGrade(grade.getSsre()), total, average+"  "+Grade.genGrade(average)};

        model.addRow(rowData);
        gradesTable.setModel(model);
        jScrollPane1.setViewportView(gradesTable);

    }//GEN-LAST:event_btnRegSearchActionPerformed

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // when clicked should go back to DASHBOARD window
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
        dash.pack();
        dash.setLocationRelativeTo(null);
        dash.setDefaultCloseOperation(dash.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewgrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewgrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewgrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewgrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewgrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClassSearch;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnRegSearch;
    private javax.swing.JComboBox<String> classLevel;
    private javax.swing.JTable gradesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField regno;
    // End of variables declaration//GEN-END:variables
}
